# Automatically generated by configure - do NOT modify!
set(LIBS 
    xutil
	xengine
)
set(TARGET_OS Android)
set(ARCH armeabi-v7a)
set(INCDIR f:/WORK/Android_SPACE/Lib/xedit/trunk/script/../include)
set(LIBDIR f:/WORK/Android_SPACE/Lib/xedit/trunk/script/../lib)
set(CMAKE_BUILD_TYPE Debug)
set(LIBRARY_OUTPUT_PATH f:/WORK/Android_SPACE/Lib/xedit/trunk/script/../lib/Android/Debug/armeabi-v7a)
set(CMAKE_RUNTIME_OUTPUT_DIRECTORY f:/WORK/Android_SPACE/Lib/xedit/trunk/script/../lib/Android/Debug/armeabi-v7a)
set(CMAKE_BINARY_DIR f:/WORK/Android_SPACE/Lib/xedit/trunk/script/../CMakeFiles/Android/Debug/armeabi-v7a)
set(INCLUDE_OUTPUT_PATH f:/WORK/Android_SPACE/Lib/xedit/trunk/script/../include)
include_directories(E:/android_config/third_ndk/ndk-bundle/sysroot/usr/include/arm-linux-androideabi)
set(ANDROID_TOOLCHAIN clang)
set(ANDROID_PLATFORM android-14)
set(ANDROID_NDK_HOME E:/android_config/third_ndk/ndk-bundle)
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS}  -IF:/WORK/Android_SPACE/Lib/xedit/trunk/third-part/include/libav -IF:/WORK/Android_SPACE/Lib/xedit/trunk/third-part/include/DsNleLib/linux/dsnlengine -IF:/WORK/Android_SPACE/Lib/xedit/trunk/third-part/include/DsNleLib/inc -IF:/WORK/Android_SPACE/Lib/xedit/trunk/third-part/include/DsNleLib/android/dsnlecore/include")
set(CMAKE_SHARED_LINKER_FLAGS "${CMAKE_SHARED_LINKER_FLAGS} -lz -lm")
set(CMAKE_STATIC_LINKER_FLAGS "${CMAKE_STATIC_LINKER_FLAGS} -lz -lm")
