# Automatically generated by configure - do NOT modify!
set(LIBAV_INC_DIR F:/WORK/Android_SPACE/Lib/xedit/dependency/libav/include)
set(LIBAV_LIB_DIR F:/WORK/Android_SPACE/Lib/xedit/dependency/libav/lib)
set(XEDIT_INC_DIR F:/WORK/Android_SPACE/Lib/xedit/trunk/include)
set(XEDIT_LIB_DIR F:/WORK/Android_SPACE/Lib/xedit/trunk/lib)
set(XEDIT_GEN_DIR F:/WORK/Android_SPACE/Lib/xedit/trunk/generated)
set(NLE_LIB_DIR F:/WORK/Android_SPACE/Lib/xedit/dependency/NLEPro/trunk/dlls/DsNleLib/linux/lib)
