# Uncomment this line to define a global platform for your project
platform :ios, '9.0'
# Uncomment this line if you're using Swift
#use_frameworks!

target 'XEdit' do
    pod 'CTAssetsPickerController', :svn => 'svn://192.168.2.3/App/libs/CTAssetsPickerController'
    pod 'PureLayout'
    pod 'SDWebImage'
end
